// example/three-big/angular-lager/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink } from '@angular/router';
import { LagerTitleComponent } from './lager-title/lager-title.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    RouterOutlet,
    LagerTitleComponent,
    RouterLink,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'angular-lager';
}

<app-lager-title title="Emils Lager"></app-lager-title>
<main class="main">
  <router-outlet />
</main>
<nav class="bottom-nav">
  <a routerLink="/products-list">Produkter</a>
  <a routerLink="/pack-list">Plocklista</a>
</nav>

// example/three-big/vue-lager/src/App.vue
<script setup>
import { RouterLink, RouterView } from 'vue-router'
import LagerTitle from './components/LagerTitle.vue'
</script>

<template>
  <LagerTitle title="Emil's lager" />
  <main class="main">
      <RouterView />
  </main>

  <nav class="bottom-nav">
    <RouterLink to="/">Produkter</RouterLink>
    <RouterLink to="/packlist">Plocklista</RouterLink>
  </nav>
</template>

<style scoped>

</style>
