// example/web-component-starter/components/product-list.js
import { apiKey, baseURL } from "../utils.js";

export default class ProductList extends HTMLElement {
    constructor() {
        super();

        this.products = [];
    }

    // connect component
    async connectedCallback() {
        const response = await fetch(`${baseURL}/products?api_key=${apiKey}`);
        const result = await response.json();

        this.products = result.data;

        this.render();
    }

    render() {
        const list = this.products.map((product) => {
            return `<single-product product='${JSON.stringify(product)}'>
                        </single-product>`;
        }).join("");

        this.innerHTML = `<h2>Produktlista</h2>${list}`;
    }
}

// example/three-big/react-lager/src/components/product-list.js
import { useEffect, useState} from 'react';
import SingleProduct from "./single-product.js";

function ProductList() {
    const [products, setProducts] = useState([]);

    const apiKey = "a1963bba7c5ad2d272f18a45b819cb55";

    useEffect(() => {
        (async () => {
            const response = await fetch(`https://lager.emilfolino.se/v2/products?api_key=${apiKey}`);
            const result = await response.json();

            setProducts(result.data);
        })();
    }, []);

    const productList = products.map((p, i) => {
        return <SingleProduct key={i} product={p} />;
    })

    return (
        <>
            <h2>Produkter</h2>
            {productList}
        </>


    );
}

export default ProductList;
